const Actions = {
  FETCH_YEARS: "YEARS/FETCH_YEARS",
  SET_YEARS: "YEARS/SET_YEARS",
  FETCH_DAYS: "YEARS/FETCH_DAYS",
  SET_DAYS: "YEARS/SET_DAYS",
  UPDATE_DAY: "YEARS/UPDATE_DAY",
  INSERT_DAY: "YEARS/INSERT_DAY",
  DELETE_DAY: "YEARS/DELETE_DAY",
  FECTH_EXCEL: "YEARS/FECTH_EXCEL",
  SET_RESULT_EXCEL: "YEARS/SET_RESULT_EXCEL",
  SET_EXPANDED_ROW: "YEARS/SET_EXPANDED_ROW",
  SET_EXPANDED_ROWS: "YEARS/SET_EXPANDED_ROWS",
};

export default Actions;
