const Actions = {
  FETCH_YEARS: "YEARS/FETCH_YEARS",
  SET_YEARS: "YEARS/SET_YEARS",
  FETCH_DAYS: "YEARS/FETCH_DAYS",
  SET_DAYS: "YEARS/SET_DAYS",
  UPDATE_DAY: "YEARS/UPDATE_DAY",
  INSERT_DAY: "YEARS/INSERT_DAY",
};

export default Actions;
