const Actions = {
  FETCH_YEARS: "YEARS/FETCH_YEARS",
  SET_YEARS: "YEARS/SET_YEARS",
  FETCH_YEAR: "YEARS/FETCH_YEAR",
  SET_YEAR: "YEARS/SET_YEAR",
  UPDATE_DAY: "YEARS/UPDATE_DAY",
};

export default Actions;
